/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://rhgrmyni7bazlj4xxhzmj4h4xi.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-inylpp6tkrdbzisnf3ar25vtwu",
    "aws_cognito_identity_pool_id": "ap-southeast-1:0c613172-be68-4155-9678-554817a2efbd",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_NExEpn6Wb",
    "aws_user_pools_web_client_id": "79c0bjvnd1vsts84e6jsiuqog1",
    "oauth": {}
};


export default awsmobile;
